{{- if .Values.backend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "vision-ai-labeler.fullname" . }}-backend
  labels:
    {{- include "vision-ai-labeler.backend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "vision-ai-labeler.backend.selectorLabels" . | nindent 4 }}
{{- end }}
