apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.fullname" . }}-frontend
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.frontend.port }}
      targetPort: {{ .Values.frontend.port }}
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "app.name" . }}
    app.kubernetes.io/component: frontend
